"""initial_schema

Revision ID: 1041c738a45f
Revises: 
Create Date: 2026-10-02 09:01:34.229542+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1041c738a45f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_overrides', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_id'), 'competitions', ['id'], unique=False)
    op.create_index(op.f('ix_competitions_slug'), 'competitions', ['slug'], unique=True)
    op.create_index(op.f('ix_competitions_status'), 'competitions', ['status'], unique=False)
    op.create_index(op.f('ix_competitions_title'), 'competitions', ['title'], unique=False)
    op.create_table('audit_logs',
    sa.Column('competition_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_competition_id'), 'audit_logs', ['competition_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_stage'), 'audit_logs', ['stage'], unique=False)
    op.create_table('competition_analyses',
    sa.Column('competition_id', sa.String(length=36), nullable=False),
    sa.Column('problem_type', sa.String(length=100), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('id_columns', sa.JSON(), nullable=False),
    sa.Column('train_file_name', sa.String(length=255), nullable=True),
    sa.Column('test_file_name', sa.String(length=255), nullable=True),
    sa.Column('sample_sub_file_name', sa.String(length=255), nullable=True),
    sa.Column('evaluation_metric', sa.String(length=100), nullable=False),
    sa.Column('metric_direction', sa.String(length=20), nullable=False),
    sa.Column('validation_strategy', sa.String(length=100), nullable=False),
    sa.Column('cv_strategy_details', sa.JSON(), nullable=False),
    sa.Column('submission_columns', sa.JSON(), nullable=False),
    sa.Column('leakage_risks', sa.JSON(), nullable=False),
    sa.Column('feature_engineering_plan', sa.JSON(), nullable=False),
    sa.Column('recommended_models', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reasoning_summary', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competition_analyses_competition_id'), 'competition_analyses', ['competition_id'], unique=True)
    op.create_index(op.f('ix_competition_analyses_id'), 'competition_analyses', ['id'], unique=False)
    op.create_table('competition_files',
    sa.Column('competition_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competition_files_category'), 'competition_files', ['category'], unique=False)
    op.create_index(op.f('ix_competition_files_competition_id'), 'competition_files', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_files_id'), 'competition_files', ['id'], unique=False)
    op.create_table('experiments',
    sa.Column('competition_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('best_cv_score', sa.Float(), nullable=True),
    sa.Column('best_model_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_competition_id'), 'experiments', ['competition_id'], unique=False)
    op.create_index(op.f('ix_experiments_id'), 'experiments', ['id'], unique=False)
    op.create_table('notebooks',
    sa.Column('competition_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('bundle_storage_path', sa.String(length=1024), nullable=True),
    sa.Column('structure_manifest', sa.JSON(), nullable=False),
    sa.Column('syntax_valid', sa.Boolean(), nullable=False),
    sa.Column('execution_valid', sa.Boolean(), nullable=False),
    sa.Column('submission_valid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebooks_competition_id'), 'notebooks', ['competition_id'], unique=False)
    op.create_index(op.f('ix_notebooks_id'), 'notebooks', ['id'], unique=False)
    op.create_table('dataset_profiles',
    sa.Column('competition_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('memory_bytes', sa.BigInteger(), nullable=False),
    sa.Column('schema_definition', sa.JSON(), nullable=False),
    sa.Column('column_profiles', sa.JSON(), nullable=False),
    sa.Column('sample_rows', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['competition_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_profiles_competition_id'), 'dataset_profiles', ['competition_id'], unique=False)
    op.create_index(op.f('ix_dataset_profiles_file_id'), 'dataset_profiles', ['file_id'], unique=False)
    op.create_index(op.f('ix_dataset_profiles_id'), 'dataset_profiles', ['id'], unique=False)
    op.create_table('model_runs',
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('model_family', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('cv_mean_score', sa.Float(), nullable=False),
    sa.Column('cv_std_score', sa.Float(), nullable=False),
    sa.Column('fold_scores', sa.JSON(), nullable=False),
    sa.Column('train_time_seconds', sa.Float(), nullable=False),
    sa.Column('feature_importances', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_experiment_id'), 'model_runs', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_model_runs_id'), 'model_runs', ['id'], unique=False)
    op.create_table('notebook_executions',
    sa.Column('notebook_id', sa.String(length=36), nullable=False),
    sa.Column('execution_status', sa.String(length=50), nullable=False),
    sa.Column('cells_executed', sa.Integer(), nullable=False),
    sa.Column('total_cells', sa.Integer(), nullable=False),
    sa.Column('runtime_seconds', sa.Float(), nullable=False),
    sa.Column('execution_log', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebook_executions_id'), 'notebook_executions', ['id'], unique=False)
    op.create_index(op.f('ix_notebook_executions_notebook_id'), 'notebook_executions', ['notebook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notebook_executions_notebook_id'), table_name='notebook_executions')
    op.drop_index(op.f('ix_notebook_executions_id'), table_name='notebook_executions')
    op.drop_table('notebook_executions')
    op.drop_index(op.f('ix_model_runs_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_experiment_id'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_dataset_profiles_id'), table_name='dataset_profiles')
    op.drop_index(op.f('ix_dataset_profiles_file_id'), table_name='dataset_profiles')
    op.drop_index(op.f('ix_dataset_profiles_competition_id'), table_name='dataset_profiles')
    op.drop_table('dataset_profiles')
    op.drop_index(op.f('ix_notebooks_id'), table_name='notebooks')
    op.drop_index(op.f('ix_notebooks_competition_id'), table_name='notebooks')
    op.drop_table('notebooks')
    op.drop_index(op.f('ix_experiments_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_competition_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_competition_files_id'), table_name='competition_files')
    op.drop_index(op.f('ix_competition_files_competition_id'), table_name='competition_files')
    op.drop_index(op.f('ix_competition_files_category'), table_name='competition_files')
    op.drop_table('competition_files')
    op.drop_index(op.f('ix_competition_analyses_id'), table_name='competition_analyses')
    op.drop_index(op.f('ix_competition_analyses_competition_id'), table_name='competition_analyses')
    op.drop_table('competition_analyses')
    op.drop_index(op.f('ix_audit_logs_stage'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_competition_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_competitions_title'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_status'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_slug'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_id'), table_name='competitions')
    op.drop_table('competitions')
    # ### end Alembic commands ###
