import nbformat as nbf
from app.llm.contracts import NotebookPlan

class NotebookGenerator:
    """Generates complete Jupyter notebooks from a NotebookPlan."""
    
    @classmethod
    def generate(cls, plan: NotebookPlan) -> nbf.NotebookNode:
        nb = nbf.v4.new_notebook()
        
        # 1. Header
        nb.cells.append(nbf.v4.new_markdown_cell(f"# {plan.competition_title}\n\nAutomated starter notebook generated by the AI Platform."))
        
        # 2. Imports
        imports = (
            "import numpy as np\n"
            "import pandas as pd\n"
            "import polars as pl\n"
            "import matplotlib.pyplot as plt\n"
            "import seaborn as sns\n\n"
            "from sklearn.model_selection import KFold, StratifiedKFold, TimeSeriesSplit\n"
            "from sklearn.metrics import mean_squared_error, log_loss, roc_auc_score\n"
            "import lightgbm as lgb\n"
            "import xgboost as xgb\n\n"
            "import warnings\n"
            "warnings.filterwarnings('ignore')\n"
        )
        nb.cells.append(nbf.v4.new_code_cell(imports))
        
        # 3. Setup and Task Overview
        nb.cells.append(nbf.v4.new_markdown_cell(
            f"## Task Overview\n"
            f"- **Problem Type:** {plan.problem_type}\n"
            f"- **Target Variable:** {plan.target_variable}\n"
            f"- **Evaluation Metric:** {plan.evaluation_metric}\n"
            f"- **Validation Strategy:** {plan.validation_strategy}"
        ))
        
        # 4. Feature Engineering section
        nb.cells.append(nbf.v4.new_markdown_cell("## Feature Engineering\n\nBased on dataset profiling, the following features are generated:"))
        
        for feat in plan.feature_engineering_ideas:
            nb.cells.append(nbf.v4.new_markdown_cell(f"### {feat.feature_name}\n{feat.description}"))
            nb.cells.append(nbf.v4.new_code_cell(feat.code_snippet))
            
        # 5. Modeling section
        nb.cells.append(nbf.v4.new_markdown_cell(
            f"## Modeling Strategy\n\n"
            f"- **Models:** {', '.join(plan.model_strategy.models_to_train)}\n"
            f"- **Ensemble:** {plan.model_strategy.ensemble_method}\n"
        ))
        
        # Dummy code for training loop outline
        modeling_code = (
            f"# Setting up {plan.validation_strategy}\n"
            f"models = {plan.model_strategy.models_to_train}\n"
            f"# Training loop would go here..."
        )
        nb.cells.append(nbf.v4.new_code_cell(modeling_code))
        
        return nb
        
    @classmethod
    def save(cls, nb: nbf.NotebookNode, path: str):
        with open(path, 'w', encoding='utf-8') as f:
            nbf.write(nb, f)

notebook_generator = NotebookGenerator()
